//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConferenceAppEntities : DbContext
    {
        public ConferenceAppEntities()
            : base("name=ConferenceAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Program> Program { get; set; }
        public virtual DbSet<ProgramMemberCategories> ProgramMemberCategories { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<File> File { get; set; }
        public virtual DbSet<ProgramPeople> ProgramPeople { get; set; }
        public virtual DbSet<Conversation> Conversation { get; set; }
        public virtual DbSet<Conference> Conference { get; set; }
        public virtual DbSet<Conversation_reply> Conversation_reply { get; set; }
        public virtual DbSet<MyAgenda> MyAgenda { get; set; }
        public virtual DbSet<SponsorPartnerCategory> SponsorPartnerCategory { get; set; }
        public virtual DbSet<SponsorsAndPartners> SponsorsAndPartners { get; set; }
        public virtual DbSet<Organizers> Organizers { get; set; }
    }
}
