//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation_reply
    {
        public int CR_ID { get; set; }
        public string Reply { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Status { get; set; }
        public Nullable<int> ConversationID { get; set; }
    
        public virtual Conversation Conversation { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
