//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public Conversation()
        {
            this.Conversation_reply = new HashSet<Conversation_reply>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserIdOne { get; set; }
        public Nullable<int> UserIdTwo { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Conversation_reply> Conversation_reply { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
