//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string FileUrl { get; set; }
        public Nullable<int> SpeakerId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
