//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.ProgramPeople = new HashSet<ProgramPeople>();
            this.MyAgenda = new HashSet<MyAgenda>();
        }
    
        public int ID { get; set; }
        public string ProgrameName { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> ConferenceID { get; set; }
        public string ProgramDescription { get; set; }
        public Nullable<System.DateTime> ProgramDate { get; set; }
        public Nullable<int> ProgramDay { get; set; }
    
        public virtual ICollection<ProgramPeople> ProgramPeople { get; set; }
        public virtual Conference Conference { get; set; }
        public virtual ICollection<MyAgenda> MyAgenda { get; set; }
    }
}
